### ISSUE TITLE
Unable to install in app, nor manually

### ISSUE THREAD

**Issue by f3bruary** [getflywheel/local-addon-instant-reload#12]
I use Local 6.3.0+5756 on Manjaro.

I'm unable to install this addon through the app. The spinner just stays stuck at the end and nothing happens.

When I try to manually install it, the yarn process errors out:

```
yarn install v1.22.17
[1/5] Validating package.json...
warning @getflywheel/local-addon-instant-reload@1.1.0: The engine "local-by-flywheel" appears to be invalid.
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > @apollo/client@3.3.6" has unmet peer dependency "graphql@^14.0.0 || ^15.0.0".
warning "@apollo/client > @graphql-typed-document-node/core@3.1.0" has unmet peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
warning "@apollo/client > graphql-tag@2.11.0" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
warning "@getflywheel/local-components > react-lowlight@2.0.0" has incorrect peer dependency "highlight.js@^9.1.0".
warning "@getflywheel/local-components > react-truncate-markup@3.0.1" has unmet peer dependency "prop-types@>=15".
warning " > react-redux@7.2.2" has unmet peer dependency "redux@^2.0.0 || ^3.0.0 || ^4.0.0-0".
warning " > subscriptions-transport-ws@0.9.18" has unmet peer dependency "graphql@>=0.10.0".
warning " > @getflywheel/eslint-config-local@1.0.4" has unmet peer dependency "babel-eslint@^10.0.1".
warning " > @getflywheel/eslint-config-local@1.0.4" has incorrect peer dependency "eslint@^5.0.0".
warning "@getflywheel/local > graphql-subscriptions@1.1.0" has incorrect peer dependency "graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning "@getflywheel/local > apollo-boost@0.1.28" has incorrect peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
warning " > babel-loader@8.2.2" has unmet peer dependency "@babel/core@^7.0.0".
warning " > react-test-renderer@17.0.1" has incorrect peer dependency "react@17.0.1".
[5/5] Building fresh packages...
success Saved lockfile.
$ yarn run build
yarn run v1.22.17
warning @getflywheel/local-addon-instant-reload@1.1.0: The engine "local-by-flywheel" appears to be invalid.
$ yarn webpack --config webpack.config.js
warning @getflywheel/local-addon-instant-reload@1.1.0: The engine "local-by-flywheel" appears to be invalid.
$ /home/f3bruary/.config/Local/addons/local-addon-instant-reload/node_modules/.bin/webpack --config webpack.config.js
[webpack-cli] Compilation finished
[webpack-cli] Compilation finished
Hash: 72c45b48f9f785601c6fea9f9023bc5eadb05c61
Version: webpack 4.44.2
Child
    Hash: 72c45b48f9f785601c6f
    Time: 2755ms
    Built at: 22/02/2022 22:29:31
              Asset      Size  Chunks         Chunk Names
        renderer.js   358 KiB       0         renderer
    renderer.js.map  1.38 MiB       0  [dev]  renderer
    Entrypoint renderer = renderer.js renderer.js.map
      [1] ../node_modules/@apollo/client/utilities/index.js + 19 modules 46.7 KiB {0} [built]
          | ../node_modules/@apollo/client/utilities/index.js 1.51 KiB [built]
          | ../node_modules/@apollo/client/utilities/graphql/directives.js 2.92 KiB [built]
          | ../node_modules/@apollo/client/utilities/graphql/fragments.js 2.57 KiB [built]
          | ../node_modules/@apollo/client/utilities/graphql/storeUtils.js 6.26 KiB [built]
          | ../node_modules/@apollo/client/utilities/graphql/getFromAST.js 4.03 KiB [built]
          | ../node_modules/@apollo/client/utilities/graphql/transform.js 10.7 KiB [built]
          | ../node_modules/@apollo/client/utilities/common/mergeDeep.js 2.63 KiB [built]
          | ../node_modules/@apollo/client/utilities/policies/pagination.js 5.85 KiB [built]
          | ../node_modules/@apollo/client/utilities/observables/Observable.js 199 bytes [built]
          | ../node_modules/@apollo/client/utilities/common/cloneDeep.js 1.03 KiB [built]
          | ../node_modules/@apollo/client/utilities/common/maybeDeepFreeze.js 771 bytes [built]
          | ../node_modules/@apollo/client/utilities/observables/iteration.js 322 bytes [built]
          | ../node_modules/@apollo/client/utilities/observables/asyncMap.js 1.59 KiB [built]
          | ../node_modules/@apollo/client/utilities/observables/Concast.js 4.67 KiB [built]
          | ../node_modules/@apollo/client/utilities/common/arrays.js 130 bytes [built]
          |     + 5 hidden modules
      [2] external "react" 42 bytes {0} [built]
     [10] external "path" 42 bytes {0} [built]
     [18] ../node_modules/fs-extra/lib/mkdirs/index.js 328 bytes {0} [built]
     [19] ../node_modules/@apollo/client/cache/index.js 488 bytes {0} [built]
     [24] ../node_modules/@apollo/client/index.js 100 bytes {0} [built]
     [25] ./renderer/store/store.ts 3.95 KiB {0} [built]
     [56] ../node_modules/fs-extra/lib/index.js 719 bytes {0} [built]
     [83] external "@getflywheel/local/renderer" 42 bytes {0} [built]
     [85] ./constants.ts 760 bytes {0} [built]
     [96] ../node_modules/react-redux/es/index.js + 24 modules 50.5 KiB {0} [built]
          | ../node_modules/react-redux/es/index.js 776 bytes [built]
          | ../node_modules/react-redux/es/components/Context.js 228 bytes [built]
          | ../node_modules/react-redux/es/utils/batch.js 413 bytes [built]
          | ../node_modules/react-redux/es/components/Provider.js 1.42 KiB [built]
          | ../node_modules/react-redux/es/components/connectAdvanced.js 18.6 KiB [built]
          | ../node_modules/react-redux/es/utils/shallowEqual.js 654 bytes [built]
          | ../node_modules/react-redux/es/connect/connect.js 4.85 KiB [built]
          | ../node_modules/react-redux/es/hooks/useStore.js 1.13 KiB [built]
          | ../node_modules/react-redux/es/hooks/useDispatch.js 1.29 KiB [built]
          | ../node_modules/react-redux/es/hooks/useSelector.js 4.37 KiB [built]
          | ../node_modules/react-redux/es/utils/reactBatchedUpdates.js 94 bytes [built]
          | ../node_modules/react-redux/es/utils/Subscription.js 2.93 KiB [built]
          | ../node_modules/react-redux/node_modules/@babel/runtime/helpers/esm/extends.js 397 bytes [built]
          | ../node_modules/react-redux/node_modules/@babel/runtime/helpers/esm/objectWithoutPropertiesLoose.js 350 bytes [built]
          | ../node_modules/react-redux/es/utils/useIsomorphicLayoutEffect.js 867 bytes [built]
          |     + 10 hidden modules
    [105] ./renderer.tsx 5.4 KiB {0} [built]
    [153] ./renderer/components/InstantReloadContent.tsx 7.8 KiB {0} [built]
    [165] ./renderer/localClient/localGraphQLClient.ts 1.75 KiB {0} [built]
    [187] ./renderer/components/StatusIndicator.tsx 1.41 KiB {0} [built]
        + 292 hidden modules

    WARNING in ../node_modules/ws/lib/BufferUtil.js
    Module not found: Error: Can't resolve 'bufferutil' in '/home/f3bruary/.config/Local/addons/local-addon-instant-reload/node_modules/ws/lib'
     @ ../node_modules/ws/lib/BufferUtil.js
     @ ../node_modules/ws/lib/Sender.js
     @ ../node_modules/ws/index.js
     @ ./renderer/localClient/localGraphQLClient.ts
     @ ./renderer.tsx

    WARNING in ../node_modules/ws/lib/Validation.js
    Module not found: Error: Can't resolve 'utf-8-validate' in '/home/f3bruary/.config/Local/addons/local-addon-instant-reload/node_modules/ws/lib'
     @ ../node_modules/ws/lib/Validation.js
     @ ../node_modules/ws/lib/Receiver.js
     @ ../node_modules/ws/index.js
     @ ./renderer/localClient/localGraphQLClient.ts
     @ ./renderer.tsx

    ERROR in ./renderer/components/InstantReloadContent.scss (../node_modules/css-loader/dist/cjs.js??ref--6-1!../node_modules/resolve-url-loader!../node_modules/sass-loader/dist/cjs.js!./renderer/components/InstantReloadContent.scss)
    Module build failed (from ../node_modules/css-loader/dist/cjs.js):
    Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /home/f3bruary/.config/Local/addons/local-addon-instant-reload/node_modules/postcss/package.json
        at new NodeError (node:internal/errors:371:5)
        at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
        at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
        at resolveExports (node:internal/modules/cjs/loader:482:36)
        at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
        at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
        at Function.Module._load (node:internal/modules/cjs/loader:778:27)
        at Module.require (node:internal/modules/cjs/loader:999:19)
        at require (/home/f3bruary/.config/Local/addons/local-addon-instant-reload/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at Object.<anonymous> (/home/f3bruary/.config/Local/addons/local-addon-instant-reload/node_modules/css-loader/dist/index.js:12:39)
        at Module._compile (/home/f3bruary/.config/Local/addons/local-addon-instant-reload/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
        at Module.load (node:internal/modules/cjs/loader:975:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Module.require (node:internal/modules/cjs/loader:999:19)
        at require (/home/f3bruary/.config/Local/addons/local-addon-instant-reload/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
     @ ./renderer/components/InstantReloadContent.scss 2:12-215 9:17-24 13:15-22
     @ ./renderer/components/InstantReloadContent.tsx
     @ ./renderer.tsx

    ERROR in ./renderer/components/StatusIndicator.scss (../node_modules/css-loader/dist/cjs.js??ref--6-1!../node_modules/resolve-url-loader!../node_modules/sass-loader/dist/cjs.js!./renderer/components/StatusIndicator.scss)
    Module build failed (from ../node_modules/css-loader/dist/cjs.js):
    Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /home/f3bruary/.config/Local/addons/local-addon-instant-reload/node_modules/postcss/package.json
        at new NodeError (node:internal/errors:371:5)
        at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
        at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
        at resolveExports (node:internal/modules/cjs/loader:482:36)
        at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
        at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
        at Function.Module._load (node:internal/modules/cjs/loader:778:27)
        at Module.require (node:internal/modules/cjs/loader:999:19)
        at require (/home/f3bruary/.config/Local/addons/local-addon-instant-reload/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at Object.<anonymous> (/home/f3bruary/.config/Local/addons/local-addon-instant-reload/node_modules/css-loader/dist/index.js:12:39)
        at Module._compile (/home/f3bruary/.config/Local/addons/local-addon-instant-reload/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
        at Module.load (node:internal/modules/cjs/loader:975:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Module.require (node:internal/modules/cjs/loader:999:19)
        at require (/home/f3bruary/.config/Local/addons/local-addon-instant-reload/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
     @ ./renderer/components/StatusIndicator.scss 2:12-210 9:17-24 13:15-22
     @ ./renderer/components/StatusIndicator.tsx
     @ ./renderer.tsx

    ERROR in ./renderer/components/ChangeLog.scss (../node_modules/css-loader/dist/cjs.js??ref--6-1!../node_modules/resolve-url-loader!../node_modules/sass-loader/dist/cjs.js!./renderer/components/ChangeLog.scss)
    Module build failed (from ../node_modules/css-loader/dist/cjs.js):
    Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /home/f3bruary/.config/Local/addons/local-addon-instant-reload/node_modules/postcss/package.json
        at new NodeError (node:internal/errors:371:5)
        at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
        at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
        at resolveExports (node:internal/modules/cjs/loader:482:36)
        at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
        at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
        at Function.Module._load (node:internal/modules/cjs/loader:778:27)
        at Module.require (node:internal/modules/cjs/loader:999:19)
        at require (/home/f3bruary/.config/Local/addons/local-addon-instant-reload/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at Object.<anonymous> (/home/f3bruary/.config/Local/addons/local-addon-instant-reload/node_modules/css-loader/dist/index.js:12:39)
        at Module._compile (/home/f3bruary/.config/Local/addons/local-addon-instant-reload/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
        at Module.load (node:internal/modules/cjs/loader:975:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Module.require (node:internal/modules/cjs/loader:999:19)
        at require (/home/f3bruary/.config/Local/addons/local-addon-instant-reload/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
     @ ./renderer/components/ChangeLog.scss 2:12-204 9:17-24 13:15-22
     @ ./renderer/components/ChangeLog.tsx
     @ ./renderer/components/InstantReloadContent.tsx
     @ ./renderer.tsx
Child
    Hash: ea9f9023bc5eadb05c61
    Time: 901ms
    Built at: 22/02/2022 22:29:30
                          Asset      Size  Chunks                   Chunk Names
        instantReloadProcess.js  4.41 KiB       0  [emitted]        instantReloadProcess
    instantReloadProcess.js.map  16.5 KiB       0  [emitted] [dev]  instantReloadProcess
                        main.js  6.58 KiB       1  [emitted]        main
                    main.js.map  19.6 KiB       1  [emitted] [dev]  main
    Entrypoint main = main.js main.js.map
    Entrypoint instantReloadProcess = instantReloadProcess.js instantReloadProcess.js.map
     [0] ./constants.ts 760 bytes {0} {1} [built]
     [1] external "path" 42 bytes {0} {1} [built]
     [2] external "@getflywheel/local/main" 42 bytes {1} [built]
     [3] ./main.ts 4.01 KiB {1} [built]
     [4] ./main/InstantReload.ts 6.56 KiB {1} [built]
     [5] external "fs-extra" 42 bytes {1} [built]
     [6] ./types.ts 284 bytes {1} [built]
     [7] ./main/instantReloadProcess.ts 9.55 KiB {0} [built]
     [8] external "fs" 42 bytes {0} [built]
     [9] external "get-port" 42 bytes {0} [built]
    [10] external "@getflywheel/local-browsersync" 42 bytes {0} [built]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by aadilayub** [comment]
Same here

**Comment by aminjabari** [comment]
me2
